services:
    app:
        container_name: telsa_app
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                UID: 1000
                GID: 1000
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - PHP_OPCACHE_REVALIDATE_FREQ=0
            - DB_HOST=db
            - REDIS_HOST=redis
        ports:
            - ${APP_PORT:-8000}:8000
            - 5173:5173
        expose:
            - ${APP_PORT:-8000}
            - 5173
        env_file:
            - .env
        volumes:
            - ./:/app
            - ./node_modules:/app/node_modules
            - ./vendor:/app/vendor
            - ./docker/entrypoint.sh:/usr/local/bin/entrypoint.sh:rw
        networks:
            - main-network
        restart: unless-stopped
        depends_on:
            - db

    db:
        container_name: telsa_db_mysql
        image: mysql:9.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE:-telsa}
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - main-network
        restart: unless-stopped

    redis:
        container_name: telsa_redis
        image: redis:8.0-alpine
        restart: unless-stopped
        volumes:
            - redis-data:/data
        networks:
            - main-network
        command: redis-server --appendonly yes

networks:
    main-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
    redis-data:
        driver: local
